// Complete AKC breeds data - Part 1: Update existing breeds with new classification fields
// This script will help us systematically update all existing breeds and add new ones

export const breedUpdates = {
  // Existing breeds - add new classification fields
  "golden-retriever": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Cold"] as const,
    coatType: "Long" as const,
    coatLength: "Long" as const,
    hypoallergenic: false,
  },
  "labrador-retriever": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Cold", "Adaptable"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "cocker-spaniel": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Long" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  "irish-setter": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Cold"] as const,
    coatType: "Long" as const,
    coatLength: "Long" as const,
    hypoallergenic: false,
  },
  "german-shorthaired-pointer": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "german-shepherd": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Cold", "Adaptable"] as const,
    coatType: "Double" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  "siberian-husky": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Cold", "Moderate"] as const,
    coatType: "Double" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  rottweiler: {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Cold"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  boxer: {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "great-dane": {
    sizeCategory: "Giant" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "doberman-pinscher": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "border-collie": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Moderate", "Cold", "Adaptable"] as const,
    coatType: "Double" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  "australian-shepherd": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Double" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  "pembroke-welsh-corgi": {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate", "Cold"] as const,
    coatType: "Double" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  "shetland-sheepdog": {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate", "Cold"] as const,
    coatType: "Double" as const,
    coatLength: "Long" as const,
    hypoallergenic: false,
  },
  "australian-cattle-dog": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Hot", "Moderate", "Adaptable"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  pomeranian: {
    sizeCategory: "Toy" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Double" as const,
    coatLength: "Long" as const,
    hypoallergenic: false,
  },
  chihuahua: {
    sizeCategory: "Toy" as const,
    climateSuitability: ["Hot", "Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "french-bulldog": {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  pug: {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "shih-tzu": {
    sizeCategory: "Toy" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Long" as const,
    coatLength: "Long" as const,
    hypoallergenic: true,
  },
  "cavalier-king-charles-spaniel": {
    sizeCategory: "Toy" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Long" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  "jack-russell-terrier": {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "yorkshire-terrier": {
    sizeCategory: "Toy" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Long" as const,
    coatLength: "Long" as const,
    hypoallergenic: true,
  },
  "bull-terrier": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "miniature-schnauzer": {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Wire" as const,
    coatLength: "Medium" as const,
    hypoallergenic: true,
  },
  "west-highland-white-terrier": {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate", "Cold"] as const,
    coatType: "Double" as const,
    coatLength: "Medium" as const,
    hypoallergenic: false,
  },
  beagle: {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  dachshund: {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "basset-hound": {
    sizeCategory: "Medium" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  greyhound: {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Hot"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  "rhodesian-ridgeback": {
    sizeCategory: "Large" as const,
    climateSuitability: ["Hot", "Moderate"] as const,
    coatType: "Short" as const,
    coatLength: "Short" as const,
    hypoallergenic: false,
  },
  goldendoodle: {
    sizeCategory: "Large" as const,
    climateSuitability: ["Moderate", "Adaptable"] as const,
    coatType: "Curly" as const,
    coatLength: "Long" as const,
    hypoallergenic: true,
  },
  maltipoo: {
    sizeCategory: "Small" as const,
    climateSuitability: ["Moderate"] as const,
    coatType: "Curly" as const,
    coatLength: "Medium" as const,
    hypoallergenic: true,
  },
};
