export const tmpFciBreeds = [
  // sheepdogs-cattledogs
  {
    id: "australian-kelpie",
    name: "Australian Kelpie",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "belgian-shepherd-dog",
    name: "Chien de Berger Belge (Belgian Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  { id: "schipperke", name: "Schipperke", group: "sheepdogs-cattledogs" },
  {
    id: "croatian-shepherd-dog",
    name: "Hrvatski Ovcar (Croatian Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "czechoslovakian-wolfdog",
    name: "Ceskoslovensky Vlciak (Czechoslovakian Wolfdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "beauce-sheepdog",
    name: "Berger de Beauce (Beauce Sheepdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "briard",
    name: "Berger de Brie (Briard)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "long-haired-pyrenean-sheepdog",
    name: "Chien de Berger des Pyrenees A Poil Long (Long-Haired Pyrenean Sheepdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "picardy-sheepdog",
    name: "Berger de Picardie (Picardy Sheepdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "pyrenean-sheepdog-smooth-faced",
    name: "Chien de Berger des Pyrenees A Face Rase (Pyrenean Sheepdog - Smooth Faced)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "german-shepherd-dog",
    name: "Deutscher Schaferhund (German Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "bearded-collie",
    name: "Bearded Collie",
    group: "sheepdogs-cattledogs",
  },
  { id: "border-collie", name: "Border Collie", group: "sheepdogs-cattledogs" },
  { id: "collie-rough", name: "Collie Rough", group: "sheepdogs-cattledogs" },
  { id: "collie-smooth", name: "Collie Smooth", group: "sheepdogs-cattledogs" },
  {
    id: "old-english-sheepdog",
    name: "Old English Sheepdog",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "shetland-sheepdog",
    name: "Shetland Sheepdog",
    group: "sheepdogs-cattledogs",
  },
  { id: "komondor", name: "Komondor", group: "sheepdogs-cattledogs" },
  { id: "kuvasz", name: "Kuvasz", group: "sheepdogs-cattledogs" },
  { id: "mudi", name: "Mudi", group: "sheepdogs-cattledogs" },
  { id: "puli", name: "Puli", group: "sheepdogs-cattledogs" },
  { id: "pumi", name: "Pumi", group: "sheepdogs-cattledogs" },
  {
    id: "abruzzes-and-maremma-shepherd-dog",
    name: "Cane da Pastore Abruzzese Maremmano (Abruzzes and Maremma Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "bergamasco-shepherd-dog",
    name: "Cane da Pastore Bergamasco (Bergamasco Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "polish-lowland-sheepdog",
    name: "Polski Owczarek Nizinny (Polish Lowland Sheepdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "polish-tatra-shepherd",
    name: "Polski Owczarek Podhalanski (Polish Tatra Shepherd)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "portuguese-sheepdog",
    name: "Cao da Serra de Aires (Portuguese Sheepdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "romanian-carpathian-shepherd-dog",
    name: "Ciobanesc Romanesc Carpatin (Romanian Carpathian Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "romanian-mioritic-shepherd-dog",
    name: "Ciobanesc Romanesc Mioritic (Romanian Mioritic Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "south-russian-shepherd-dog",
    name: "Yuzhnorusskaya Ovcharka (South Russian Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "slovakian-chuvach",
    name: "Slovensky Cuvac (Slovakian Chuvach)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "catalan-sheepdog",
    name: "Gos D'Atura Catala (Catalan Sheepdog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "majorca-shepherd-dog",
    name: "Ca de Bestiar (Majorca Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "white-swiss-shepherd-dog",
    name: "Berger Blanc Suisse (White Swiss Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "dutch-schapendoes",
    name: "Nederlandse Schapendoes (Dutch Schapendoes)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "dutch-shepherd-dog",
    name: "Hollandse Herdershond (Dutch Shepherd Dog)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "saarloos-wolfhond",
    name: "Saarlooswolfhond (Saarloos Wolfhond)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "australian-shepherd",
    name: "Australian Shepherd",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "australian-cattle-dog",
    name: "Australian Cattle Dog",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "bouvier-des-ardennes",
    name: "Bouvier des Ardennes",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "bouvier-des-flandres",
    name: "Bouvier des Flandres-Vlaamse Koehond (Bouvier des Flandres)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "cardigan",
    name: "Welsh Corgi (Cardigan)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "pembroke",
    name: "Welsh Corgi (Pembroke)",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "miniature-american-shepherd",
    name: "Miniature American Shepherd",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "bohemian-shepherd-dog",
    name: "Bohemian Shepherd Dog",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "lancashire-heeler",
    name: "Lancashire Heeler",
    group: "sheepdogs-cattledogs",
  },
  {
    id: "australian-stumpy-tail-cattle-dog",
    name: "Australian Stumpy Tail Cattle Dog",
    group: "sheepdogs-cattledogs",
  },
  // pinscher-schnauzer-molossoid-swiss
  {
    id: "austrian-pinscher",
    name: "Osterreichischer Pinscher (Austrian Pinscher)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "danish-swedish-farmdog",
    name: "Dansk-Svensk Gardshund (Danish-Swedish Farmdog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "affenpinscher",
    name: "Affenpinscher",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "dobermann",
    name: "Dobermann",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "german-pinscher",
    name: "Deutscher Pinscher (German Pinscher)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "miniature-pinscher",
    name: "Zwergpinscher (Miniature Pinscher)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "giant-schnauzer",
    name: "Riesenschnauzer (Giant Schnauzer)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "miniature-schnauzer",
    name: "Zwergschnauzer (Miniature Schnauzer)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "schnauzer",
    name: "Schnauzer",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "dutch-smoushond",
    name: "Hollandse Smoushond (Dutch Smoushond)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "russian-black-terrier",
    name: "Russkiy Tchiorny Terrier (Russian Black Terrier)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "dogo-argentino",
    name: "Dogo Argentino",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "fila-brasileiro",
    name: "Fila Brasileiro",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "shar-pei",
    name: "Shar Pei",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "broholmer",
    name: "Broholmer",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "dogue-de-bordeaux",
    name: "Dogue de Bordeaux",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "boxer",
    name: "Deutscher Boxer (Boxer)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "great-dane",
    name: "Deutsche Dogge (Great Dane)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "rottweiler",
    name: "Rottweiler",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "bulldog",
    name: "Bulldog",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "bullmastiff",
    name: "Bullmastiff",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "mastiff",
    name: "Mastiff",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "italian-cane-corso",
    name: "Cane Corso Italiano (Italian Cane Corso)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "neapolitan-mastiff",
    name: "Mastino Napoletano (Neapolitan Mastiff)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  { id: "tosa", name: "Tosa", group: "pinscher-schnauzer-molossoid-swiss" },
  {
    id: "saint-miguel-cattle-dog",
    name: "Cao Fila de Sao Miguel (Saint Miguel Cattle Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "majorca-mastiff",
    name: "Perro Dogo Mallorquin (Majorca Mastiff)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "presa-canario",
    name: "Presa Canario",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "cimarron-uruguayo",
    name: "Cimarron Uruguayo",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "bosnian-and-herzegovinian-croatian-shepherd-dog",
    name: "Tornjak (Bosnian and Herzegovinian - Croatian Shepherd Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "newfoundland",
    name: "Newfoundland",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "pyrenean-mountain-dog",
    name: "Chien de Montagne des Pyrenees (Pyrenean Mountain Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "hovawart",
    name: "Hovawart",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "leonberger",
    name: "Leonberger",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "landseer-european-continental-type",
    name: "Landseer (European Continental Type)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "atlas-mountain-dog-aidi",
    name: "Atlas Mountain Dog (Aidi)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "yugoslavian-shepherd-dog-sharplanina",
    name: "Jugoslovenski Ovcarski Pas-Sarplaninac (Yugoslavian Shepherd Dog - Sharplanina)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "castro-laboreiro-dog",
    name: "Cao de Castro Laboreiro (Castro Laboreiro Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "estrela-mountain-dog",
    name: "Cao da Serra da Estrela (Estrela Mountain Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "rafeiro-of-alentejo",
    name: "Rafeiro Do Alentejo (Rafeiro of Alentejo)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "romanian-bucovina-shepherd",
    name: "Ciobanesc Romanesc de Bucovina (Romanian Bucovina Shepherd)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "caucasian-shepherd-dog",
    name: "Kavkazskaia Ovtcharka (Caucasian Shepherd Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "central-asia-shepherd-dog",
    name: "Sredneasiatskaya Ovtcharka (Central Asia Shepherd Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "karst-shepherd-dog",
    name: "Kraski Ovcar (Karst Shepherd Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "pyrenean-mastiff",
    name: "Mastin del Pirineo (Pyrenean Mastiff)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "spanish-mastiff",
    name: "Mastin Espanol (Spanish Mastiff)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "st-bernard",
    name: "St.Bernhardshund - Bernhardiner (St. Bernard)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "tibetan-mastiff",
    name: "Do-Khyi (Tibetan Mastiff)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "kangal-shepherd-dog",
    name: "Kangal Coban Kopegi (Kangal Shepherd Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "appenzell-cattle-dog",
    name: "Appenzeller Sennenhund (Appenzell Cattle Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "bernese-mountain-dog",
    name: "Berner Sennenhund (Bernese Mountain Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "entlebuch-cattle-dog",
    name: "Entlebucher Sennenhund (Entlebuch Cattle Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "great-swiss-mountain-dog",
    name: "Grosser Schweizer Sennenhund (Great Swiss Mountain Dog)",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "brazilian-campeiro-bulldog",
    name: "Brazilian Campeiro Bulldog",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "romanian-raven-shepherd-dog",
    name: "Romanian Raven Shepherd Dog",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "continental-bulldog",
    name: "Continental Bulldog",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  {
    id: "transmontano-mastiff",
    name: "Transmontano Mastiff",
    group: "pinscher-schnauzer-molossoid-swiss",
  },
  // terriers
  {
    id: "brazilian-terrier",
    name: "Terrier Brasileiro (Brazilian Terrier)",
    group: "terriers",
  },
  {
    id: "german-hunting-terrier",
    name: "Deutscher Jagdterrier (German Hunting Terrier)",
    group: "terriers",
  },
  { id: "airedale-terrier", name: "Airedale Terrier", group: "terriers" },
  { id: "bedlington-terrier", name: "Bedlington Terrier", group: "terriers" },
  { id: "border-terrier", name: "Border Terrier", group: "terriers" },
  { id: "fox-terrier-smooth", name: "Fox Terrier (Smooth)", group: "terriers" },
  { id: "fox-terrier-wire", name: "Fox Terrier (Wire)", group: "terriers" },
  { id: "lakeland-terrier", name: "Lakeland Terrier", group: "terriers" },
  { id: "manchester-terrier", name: "Manchester Terrier", group: "terriers" },
  {
    id: "parson-russell-terrier",
    name: "Parson Russell Terrier",
    group: "terriers",
  },
  { id: "welsh-terrier", name: "Welsh Terrier", group: "terriers" },
  {
    id: "irish-glen-of-imaal-terrier",
    name: "Irish Glen of Imaal Terrier",
    group: "terriers",
  },
  {
    id: "irish-soft-coated-wheaten-terrier",
    name: "Irish Soft Coated Wheaten Terrier",
    group: "terriers",
  },
  { id: "irish-terrier", name: "Irish Terrier", group: "terriers" },
  { id: "kerry-blue-terrier", name: "Kerry Blue Terrier", group: "terriers" },
  { id: "australian-terrier", name: "Australian Terrier", group: "terriers" },
  {
    id: "czech-terrier",
    name: "Cesky Terier (Czech Terrier)",
    group: "terriers",
  },
  { id: "cairn-terrier", name: "Cairn Terrier", group: "terriers" },
  {
    id: "dandie-dinmont-terrier",
    name: "Dandie Dinmont Terrier",
    group: "terriers",
  },
  {
    id: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    group: "terriers",
  },
  { id: "norfolk-terrier", name: "Norfolk Terrier", group: "terriers" },
  { id: "norwich-terrier", name: "Norwich Terrier", group: "terriers" },
  { id: "scottish-terrier", name: "Scottish Terrier", group: "terriers" },
  { id: "sealyham-terrier", name: "Sealyham Terrier", group: "terriers" },
  { id: "skye-terrier", name: "Skye Terrier", group: "terriers" },
  {
    id: "west-highland-white-terrier",
    name: "West Highland White Terrier",
    group: "terriers",
  },
  {
    id: "japanese-terrier",
    name: "Nihon Teria (Japanese Terrier)",
    group: "terriers",
  },
  { id: "bull-terrier", name: "Bull Terrier", group: "terriers" },
  {
    id: "miniature-bull-terrier",
    name: "Miniature Bull Terrier",
    group: "terriers",
  },
  {
    id: "staffordshire-bull-terrier",
    name: "Staffordshire Bull Terrier",
    group: "terriers",
  },
  {
    id: "american-staffordshire-terrier",
    name: "American Staffordshire Terrier",
    group: "terriers",
  },
  {
    id: "australian-silky-terrier",
    name: "Australian Silky Terrier",
    group: "terriers",
  },
  {
    id: "english-toy-terrier-black-andtan",
    name: "English Toy Terrier (English Toy Terrier (Black &Tan))",
    group: "terriers",
  },
  { id: "yorkshire-terrier", name: "Yorkshire Terrier", group: "terriers" },
  {
    id: "andalusian-terrier-sherry-terrier",
    name: "Andalusian Terrier, Sherry Terrier",
    group: "terriers",
  },
  { id: "valencian-terrier", name: "Valencian Terrier", group: "terriers" },
  // dachshunds
  { id: "dachshund", name: "Dachshund", group: "dachshunds" },
  // spitz-primitive
  {
    id: "canadian-eskimo-dog",
    name: "Canadian Eskimo Dog",
    group: "spitz-primitive",
  },
  {
    id: "greenland-dog",
    name: "Grnlandshund (Greenland Dog)",
    group: "spitz-primitive",
  },
  {
    id: "samoyed",
    name: "Samoiedskaia Sabaka (Samoyed)",
    group: "spitz-primitive",
  },
  {
    id: "alaskan-malamute",
    name: "Alaskan Malamute",
    group: "spitz-primitive",
  },
  { id: "siberian-husky", name: "Siberian Husky", group: "spitz-primitive" },
  {
    id: "finnish-spitz",
    name: "Suomenpystykorva (Finnish Spitz)",
    group: "spitz-primitive",
  },
  {
    id: "karelian-bear-dog",
    name: "Karjalankarhukoira (Karelian Bear Dog)",
    group: "spitz-primitive",
  },
  {
    id: "norwegian-elkhound-black",
    name: "Norsk Elghund Sort (Norwegian Elkhound Black)",
    group: "spitz-primitive",
  },
  {
    id: "norwegian-elkhound-grey",
    name: "Norsk Elghund Gra (Norwegian Elkhound Grey)",
    group: "spitz-primitive",
  },
  {
    id: "norwegian-lundehund",
    name: "Norsk Lundehund (Norwegian Lundehund)",
    group: "spitz-primitive",
  },
  {
    id: "east-siberian-laika",
    name: "Vostotchno-Sibirskaia Laika (East Siberian Laika)",
    group: "spitz-primitive",
  },
  {
    id: "russian-european-laika",
    name: "Russko-Evropeiskaia Laika (Russian-European Laika)",
    group: "spitz-primitive",
  },
  {
    id: "west-siberian-laika",
    name: "Zapadno-Sibirskaia Laika (West Siberian Laika)",
    group: "spitz-primitive",
  },
  { id: "jamthund", name: "Jamthund", group: "spitz-primitive" },
  {
    id: "norrbottenspitz",
    name: "Norrbottenspets (Norrbottenspitz)",
    group: "spitz-primitive",
  },
  {
    id: "finnish-lapponian-dog",
    name: "Suomenlapinkoira (Finnish Lapponian Dog)",
    group: "spitz-primitive",
  },
  {
    id: "lapponian-herder",
    name: "Lapinporokoira (Lapponian Herder)",
    group: "spitz-primitive",
  },
  {
    id: "icelandic-sheepdog",
    name: "Islenskur Fjarhundur (Icelandic Sheepdog)",
    group: "spitz-primitive",
  },
  {
    id: "norwegian-buhund",
    name: "Norsk Buhund (Norwegian Buhund)",
    group: "spitz-primitive",
  },
  {
    id: "swedish-lapphund",
    name: "Svensk Lapphund (Swedish Lapphund)",
    group: "spitz-primitive",
  },
  {
    id: "swedish-vallhund",
    name: "Vastgotaspets (Swedish Vallhund)",
    group: "spitz-primitive",
  },
  {
    id: "german-spitz",
    name: "Deutscher Spitz (German Spitz)",
    group: "spitz-primitive",
  },
  {
    id: "italian-volpino",
    name: "Volpino Italiano (Italian Volpino)",
    group: "spitz-primitive",
  },
  { id: "chow-chow", name: "Chow Chow", group: "spitz-primitive" },
  { id: "eurasian", name: "Eurasier (Eurasian)", group: "spitz-primitive" },
  { id: "akita", name: "Akita", group: "spitz-primitive" },
  { id: "american-akita", name: "American Akita", group: "spitz-primitive" },
  { id: "hokkaido", name: "Hokkaido", group: "spitz-primitive" },
  {
    id: "japanese-spitz",
    name: "Nihon Supittsu (Japanese Spitz)",
    group: "spitz-primitive",
  },
  { id: "kai", name: "Kai", group: "spitz-primitive" },
  { id: "kishu", name: "Kishu", group: "spitz-primitive" },
  { id: "shiba", name: "Shiba", group: "spitz-primitive" },
  { id: "shikoku", name: "Shikoku", group: "spitz-primitive" },
  { id: "korea-jindo-dog", name: "Korea Jindo Dog", group: "spitz-primitive" },
  {
    id: "thai-bangkaew-dog",
    name: "Thai Bangkaew Dog",
    group: "spitz-primitive",
  },
  { id: "basenji", name: "Basenji", group: "spitz-primitive" },
  { id: "canaan-dog", name: "Canaan Dog", group: "spitz-primitive" },
  { id: "pharaoh-hound", name: "Pharaoh Hound", group: "spitz-primitive" },
  { id: "xoloitzcuintle", name: "Xoloitzcuintle", group: "spitz-primitive" },
  {
    id: "peruvian-hairless-dog",
    name: "Perro Sin Pelo del Peru (Peruvian Hairless Dog)",
    group: "spitz-primitive",
  },
  {
    id: "cirneco-delletna",
    name: "Cirneco Dell'Etna",
    group: "spitz-primitive",
  },
  {
    id: "portuguese-warren-hound-portuguese-podengo",
    name: "Podengo Portugues (Portuguese Warren Hound-Portuguese Podengo)",
    group: "spitz-primitive",
  },
  {
    id: "canarian-warren-hound",
    name: "Podenco Canario (Canarian Warren Hound)",
    group: "spitz-primitive",
  },
  {
    id: "ibizan-podenco",
    name: "Podenco Ibicenco (Ibizan Podenco)",
    group: "spitz-primitive",
  },
  { id: "taiwan-dog", name: "Taiwan Dog", group: "spitz-primitive" },
  {
    id: "thai-ridgeback-dog",
    name: "Thai Ridgeback Dog",
    group: "spitz-primitive",
  },
  { id: "yakutian-laika", name: "Yakutian Laika", group: "spitz-primitive" },
  {
    id: "kintamani-bali-dog",
    name: "Kintamani-Bali Dog",
    group: "spitz-primitive",
  },
  // scent-hounds
  {
    id: "bloodhound",
    name: "Chien de Saint Hubert (Bloodhound)",
    group: "scent-hounds",
  },
  {
    id: "brazilian-tracker",
    name: "Rastreador Brasileiro (Brazilian Tracker)",
    group: "scent-hounds",
  },
  { id: "billy", name: "Billy", group: "scent-hounds" },
  {
    id: "french-tricolour-hound",
    name: "Francais Tricolore (French Tricolour Hound)",
    group: "scent-hounds",
  },
  {
    id: "french-white-and-black-hound",
    name: "Francais Blanc Et Noir (French White & Black Hound)",
    group: "scent-hounds",
  },
  {
    id: "french-white-and-orange-hound",
    name: "Francais Blanc Et Orange (French White and Orange Hound)",
    group: "scent-hounds",
  },
  {
    id: "gascon-saintongeois",
    name: "Gascon Saintongeois",
    group: "scent-hounds",
  },
  {
    id: "grand-griffon-vendeen",
    name: "Grand Griffon Vendeen",
    group: "scent-hounds",
  },
  {
    id: "great-anglo-french-tricolour-hound",
    name: "Grand Anglo-Francais Tricolore (Great Anglo-French Tricolour Hound)",
    group: "scent-hounds",
  },
  {
    id: "great-anglo-french-white-and-orange-hound",
    name: "Grand Anglo-Francais Blanc Et Orange (Great Anglo-French White & Orange Hound)",
    group: "scent-hounds",
  },
  {
    id: "great-anglo-french-white-and-black-hound",
    name: "Grand Anglo-Francais Blanc Et Noir (Great Anglo-French White and Black Hound)",
    group: "scent-hounds",
  },
  {
    id: "great-gascony-blue",
    name: "Grand Bleu de Gascogne (Great Gascony Blue)",
    group: "scent-hounds",
  },
  { id: "poitevin", name: "Poitevin", group: "scent-hounds" },
  { id: "english-foxhound", name: "English Foxhound", group: "scent-hounds" },
  { id: "otterhound", name: "Otterhound", group: "scent-hounds" },
  {
    id: "polish-hound",
    name: "Ogar Polski (Polish Hound)",
    group: "scent-hounds",
  },
  { id: "american-foxhound", name: "American Foxhound", group: "scent-hounds" },
  {
    id: "black-and-tan-coonhound",
    name: "Black and Tan Coonhound",
    group: "scent-hounds",
  },
  {
    id: "austrian-black-and-tan-hound",
    name: "Austrian Black and Tan Hound",
    group: "scent-hounds",
  },
  {
    id: "coarse-haired-styrian-hound",
    name: "Steirische Rauhhaarbracke (Coarse-Haired Styrian Hound)",
    group: "scent-hounds",
  },
  {
    id: "tyrolean-hound",
    name: "Tiroler Bracke (Tyrolean Hound)",
    group: "scent-hounds",
  },
  {
    id: "bosnian-broken-haired-hound-called-barak",
    name: "Bosanski Ostrodlaki Gonic-Barak (Bosnian Broken-Haired Hound - Called Barak)",
    group: "scent-hounds",
  },
  {
    id: "istrian-short-haired-hound",
    name: "Istarski Kratkodlaki Gonic (Istrian Short-Haired Hound)",
    group: "scent-hounds",
  },
  {
    id: "istrian-wire-haired-hound",
    name: "Istarski Ostrodlaki Gonic (Istrian Wire-Haired Hound)",
    group: "scent-hounds",
  },
  {
    id: "posavatz-hound",
    name: "Posavski Gonic (Posavatz Hound)",
    group: "scent-hounds",
  },
  {
    id: "finnish-hound",
    name: "Suomenajokoira (Finnish Hound)",
    group: "scent-hounds",
  },
  { id: "ariegeois", name: "Ariegeois", group: "scent-hounds" },
  {
    id: "artois-hound",
    name: "Chien D'Artois (Artois Hound)",
    group: "scent-hounds",
  },
  {
    id: "beagle-harrier",
    name: "Beagle-Harrier (Beagle Harrier)",
    group: "scent-hounds",
  },
  {
    id: "blue-gascony-griffon",
    name: "Griffon Bleu de Gascogne (Blue Gascony Griffon)",
    group: "scent-hounds",
  },
  {
    id: "briquet-griffon-vendeen",
    name: "Briquet Griffon Vendeen",
    group: "scent-hounds",
  },
  {
    id: "fawn-brittany-griffon",
    name: "Griffon Fauve de Bretagne (Fawn Brittany Griffon)",
    group: "scent-hounds",
  },
  { id: "griffon-nivernais", name: "Griffon Nivernais", group: "scent-hounds" },
  {
    id: "medium-sized-anglo-french-hound",
    name: "Anglo-Francais de Petite Venerie (Medium-Sized Anglo-French Hound)",
    group: "scent-hounds",
  },
  { id: "porcelaine", name: "Porcelaine", group: "scent-hounds" },
  {
    id: "small-blue-gascony",
    name: "Petit Bleu de Gascogne (Small Blue Gascony)",
    group: "scent-hounds",
  },
  { id: "harrier", name: "Harrier", group: "scent-hounds" },
  {
    id: "hellenic-hound",
    name: "Hellinikos Ichnilatis (Hellenic Hound)",
    group: "scent-hounds",
  },
  {
    id: "hungarian-hound-transylvanian-scent-hound",
    name: "Erdelyi Kopo (Hungarian Hound - Transylvanian Scent Hound)",
    group: "scent-hounds",
  },
  {
    id: "italian-rough-haired-segugio",
    name: "Segugio Italiano A Pelo Forte (Italian Rough-Haired Segugio)",
    group: "scent-hounds",
  },
  {
    id: "italian-short-haired-segugio",
    name: "Segugio Italiano A Pelo Raso (Italian Short-Haired Segugio)",
    group: "scent-hounds",
  },
  {
    id: "montenegrin-mountain-hound",
    name: "Crnogorski Planinski Gonic (Montenegrin Mountain Hound)",
    group: "scent-hounds",
  },
  {
    id: "halden-hound",
    name: "Haldenstver (Halden Hound)",
    group: "scent-hounds",
  },
  { id: "hygen-hound", name: "Hygenhund (Hygen Hound)", group: "scent-hounds" },
  {
    id: "norwegian-hound",
    name: "Dunker (Norwegian Hound)",
    group: "scent-hounds",
  },
  {
    id: "polish-hunting-dog",
    name: "Gonczy Polski (Polish Hunting Dog)",
    group: "scent-hounds",
  },
  {
    id: "serbian-hound",
    name: "Srpski Gonic (Serbian Hound)",
    group: "scent-hounds",
  },
  {
    id: "serbian-tricolour-hound",
    name: "Srpski Trobojni Gonic (Serbian Tricolour Hound)",
    group: "scent-hounds",
  },
  {
    id: "slovakian-hound",
    name: "Slovensky Kopov (Slovakian Hound)",
    group: "scent-hounds",
  },
  {
    id: "spanish-hound",
    name: "Sabueso Espanol (Spanish Hound)",
    group: "scent-hounds",
  },
  { id: "hamiltonstovare", name: "Hamiltonstovare", group: "scent-hounds" },
  { id: "schillerstovare", name: "Schillerstovare", group: "scent-hounds" },
  { id: "smalandsstovare", name: "Smalandsstovare", group: "scent-hounds" },
  {
    id: "swiss-hound",
    name: "Schweizer Laufhund - Chien Courant Suisse (Swiss Hound)",
    group: "scent-hounds",
  },
  {
    id: "basset-fauve-de-bretagne",
    name: "Basset Fauve de Bretagne",
    group: "scent-hounds",
  },
  {
    id: "blue-gascony-basset",
    name: "Basset Bleu de Gascogne (Blue Gascony Basset)",
    group: "scent-hounds",
  },
  {
    id: "grand-basset-griffon-vendeen",
    name: "Grand Basset Griffon Vendeen",
    group: "scent-hounds",
  },
  {
    id: "norman-artesien-basset",
    name: "Basset Artesien Normand (Norman Artesien Basset)",
    group: "scent-hounds",
  },
  {
    id: "petit-basset-griffon-vendeen",
    name: "Petit Basset Griffon Vendeen",
    group: "scent-hounds",
  },
  {
    id: "german-hound",
    name: "Deutsche Bracke (German Hound)",
    group: "scent-hounds",
  },
  {
    id: "westphalian-dachsbracke",
    name: "Westfalische Dachsbracke (Westphalian Dachsbracke)",
    group: "scent-hounds",
  },
  { id: "basset-hound", name: "Basset Hound", group: "scent-hounds" },
  { id: "beagle", name: "Beagle", group: "scent-hounds" },
  { id: "drever", name: "Drever", group: "scent-hounds" },
  {
    id: "small-swiss-hound",
    name: "Schweizer Niederlaufhund (Small Swiss Hound)",
    group: "scent-hounds",
  },
  {
    id: "alpine-dachsbracke",
    name: "Alpenlandische Dachsbracke (Alpine Dachsbracke)",
    group: "scent-hounds",
  },
  {
    id: "bavarian-mountain-scent-hound",
    name: "Bayerischer Gebirgsschweisshund (Bavarian Mountain Scent Hound)",
    group: "scent-hounds",
  },
  {
    id: "hanoverian-scent-hound",
    name: "Hannoverscher Schweisshund (Hanoverian Scent Hound)",
    group: "scent-hounds",
  },
  {
    id: "dalmatian",
    name: "Dalmatinski Pas (Dalmatian)",
    group: "scent-hounds",
  },
  {
    id: "rhodesian-ridgeback",
    name: "Rhodesian Ridgeback",
    group: "scent-hounds",
  },
  { id: "estonian-hound", name: "Estonian Hound", group: "scent-hounds" },
  { id: "segugio-maremmano", name: "Segugio Maremmano", group: "scent-hounds" },
  // pointing-dogs
  {
    id: "old-danish-pointing-dog",
    name: "Gammel Dansk Hnsehund (Old Danish Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "ariege-pointing-dog",
    name: "Braque de L'Ariege (Ariege Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "auvergne-pointer",
    name: "Braque D'Auvergne (Auvergne Pointer)",
    group: "pointing-dogs",
  },
  {
    id: "bourbonnais-pointing-dog",
    name: "Braque du Bourbonnais (Bourbonnais Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "french-pointing-dog-gascogne-type",
    name: "Braque Francais - Type Gascogne (French Pointing Dog - Gascogne Type)",
    group: "pointing-dogs",
  },
  {
    id: "french-pointing-dog-pyrenean-type",
    name: "Braque Francais - Type Pyrenees (French Pointing Dog - Pyrenean Type)",
    group: "pointing-dogs",
  },
  {
    id: "saint-germain-pointer",
    name: "Braque Saint-Germain (Saint Germain Pointer)",
    group: "pointing-dogs",
  },
  {
    id: "deutsch-stichelhaar",
    name: "Deutsch Stichelhaar",
    group: "pointing-dogs",
  },
  {
    id: "german-short-haired-pointing-dog",
    name: "Deutsch Kurzhaar (German Short- Haired Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "german-wire-haired-pointing-dog",
    name: "Deutsch Drahthaar (German Wire- Haired Pointing Dog)",
    group: "pointing-dogs",
  },
  { id: "pudelpointer", name: "Pudelpointer", group: "pointing-dogs" },
  { id: "weimaraner", name: "Weimaraner", group: "pointing-dogs" },
  {
    id: "hungarian-short-haired-pointer-vizsla",
    name: "Rovidszoru Magyar Vizsla (Hungarian Short-Haired Pointer (Vizsla))",
    group: "pointing-dogs",
  },
  {
    id: "hungarian-wire-haired-pointer",
    name: "Drotzoru Magyar Vizsla (Hungarian Wire-Haired Pointer)",
    group: "pointing-dogs",
  },
  {
    id: "italian-pointing-dog",
    name: "Bracco Italiano (Italian Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "portuguese-pointing-dog",
    name: "Perdigueiro Portugues (Portuguese Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "wirehaired-slovakian-pointer",
    name: "Wirehaired Slovakian Pointer",
    group: "pointing-dogs",
  },
  {
    id: "burgos-pointing-dog",
    name: "Perdiguero de Burgos (Burgos Pointing Dog)",
    group: "pointing-dogs",
  },
  {
    id: "blue-picardy-spaniel",
    name: "Epagneul Bleu de Picardie (Blue Picardy Spaniel)",
    group: "pointing-dogs",
  },
  {
    id: "brittany-spaniel",
    name: "Epagneul Breton (Brittany Spaniel)",
    group: "pointing-dogs",
  },
  {
    id: "french-spaniel",
    name: "Epagneul Francais (French Spaniel)",
    group: "pointing-dogs",
  },
  {
    id: "picardy-spaniel",
    name: "Epagneul Picard (Picardy Spaniel)",
    group: "pointing-dogs",
  },
  {
    id: "pont-audemer-spaniel",
    name: "Epagneul de Pont-Audemer (Pont-Audemer Spaniel)",
    group: "pointing-dogs",
  },
  { id: "deutsch-langhaar", name: "Deutsch Langhaar", group: "pointing-dogs" },
  {
    id: "kleiner-munsterlander",
    name: "Kleiner Munsterlander",
    group: "pointing-dogs",
  },
  {
    id: "large-munsterlander",
    name: "Grosser Munsterlander Vorstehhund (Large Munsterlander)",
    group: "pointing-dogs",
  },
  {
    id: "drentsche-partridge-dog",
    name: "Drentsche Patrijshond (Drentsche Partridge Dog)",
    group: "pointing-dogs",
  },
  { id: "stabijhoun", name: "Stabijhoun", group: "pointing-dogs" },
  {
    id: "bohemian-wire-haired-pointing-griffon",
    name: "Cesky Fousek (Bohemian Wire-Haired Pointing Griffon)",
    group: "pointing-dogs",
  },
  {
    id: "wire-haired-pointing-griffon-korthals",
    name: "Griffon A Poil Dur Korthals (Wire-Haired Pointing Griffon Korthals)",
    group: "pointing-dogs",
  },
  {
    id: "italian-spinone",
    name: "Spinone Italiano (Italian Spinone)",
    group: "pointing-dogs",
  },
  { id: "english-pointer", name: "English Pointer", group: "pointing-dogs" },
  { id: "english-setter", name: "English Setter", group: "pointing-dogs" },
  { id: "gordon-setter", name: "Gordon Setter", group: "pointing-dogs" },
  {
    id: "irish-red-and-white-setter",
    name: "Irish Red and White Setter",
    group: "pointing-dogs",
  },
  { id: "irish-red-setter", name: "Irish Red Setter", group: "pointing-dogs" },
  // retrievers-flushing-water
  {
    id: "nova-scotia-duck-tolling-retriever",
    name: "Nova Scotia Duck Tolling Retriever",
    group: "retrievers-flushing-water",
  },
  {
    id: "curly-coated-retriever",
    name: "Curly Coated Retriever",
    group: "retrievers-flushing-water",
  },
  {
    id: "flat-coated-retriever",
    name: "Flat Coated Retriever",
    group: "retrievers-flushing-water",
  },
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    group: "retrievers-flushing-water",
  },
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    group: "retrievers-flushing-water",
  },
  {
    id: "chesapeake-bay-retriever",
    name: "Chesapeake Bay Retriever",
    group: "retrievers-flushing-water",
  },
  {
    id: "german-spaniel",
    name: "Deutscher Wachtelhund (German Spaniel)",
    group: "retrievers-flushing-water",
  },
  {
    id: "clumber-spaniel",
    name: "Clumber Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "english-cocker-spaniel",
    name: "English Cocker Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "english-springer-spaniel",
    name: "English Springer Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "field-spaniel",
    name: "Field Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "sussex-spaniel",
    name: "Sussex Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "welsh-springer-spaniel",
    name: "Welsh Springer Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "nederlandse-kooikerhondje",
    name: "Nederlandse Kooikerhondje",
    group: "retrievers-flushing-water",
  },
  {
    id: "american-cocker-spaniel",
    name: "American Cocker Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "french-water-dog",
    name: "Barbet (French Water Dog)",
    group: "retrievers-flushing-water",
  },
  {
    id: "irish-water-spaniel",
    name: "Irish Water Spaniel",
    group: "retrievers-flushing-water",
  },
  {
    id: "romagna-water-dog",
    name: "Lagotto Romagnolo (Romagna Water Dog)",
    group: "retrievers-flushing-water",
  },
  {
    id: "portuguese-water-dog",
    name: "Cao de Agua Portugues (Portuguese Water Dog)",
    group: "retrievers-flushing-water",
  },
  {
    id: "spanish-water-dog",
    name: "Perro de Agua Espanol (Spanish Water Dog)",
    group: "retrievers-flushing-water",
  },
  { id: "wetterhoun", name: "Wetterhoun", group: "retrievers-flushing-water" },
  {
    id: "american-water-spaniel",
    name: "American Water Spaniel",
    group: "retrievers-flushing-water",
  },
  // companion-toy
  {
    id: "bichon-frise",
    name: "Bichon A Poil Frise (Bichon Frise)",
    group: "companion-toy",
  },
  { id: "maltese", name: "Maltese", group: "companion-toy" },
  {
    id: "havanese",
    name: "Bichon Havanais (Havanese)",
    group: "companion-toy",
  },
  { id: "bolognese", name: "Bolognese", group: "companion-toy" },
  { id: "coton-de-tulear", name: "Coton de Tulear", group: "companion-toy" },
  {
    id: "little-lion-dog",
    name: "Petit Chien Lion (Little Lion Dog)",
    group: "companion-toy",
  },
  { id: "poodle", name: "Caniche (Poodle)", group: "companion-toy" },
  { id: "griffon-belge", name: "Griffon Belge", group: "companion-toy" },
  {
    id: "griffon-bruxellois",
    name: "Griffon Bruxellois",
    group: "companion-toy",
  },
  { id: "petit-brabancon", name: "Petit Brabancon", group: "companion-toy" },
  {
    id: "chinese-crested-dog",
    name: "Chinese Crested Dog",
    group: "companion-toy",
  },
  { id: "lhasa-apso", name: "Lhasa Apso", group: "companion-toy" },
  { id: "shih-tzu", name: "Shih Tzu", group: "companion-toy" },
  { id: "tibetan-spaniel", name: "Tibetan Spaniel", group: "companion-toy" },
  { id: "tibetan-terrier", name: "Tibetan Terrier", group: "companion-toy" },
  { id: "chihuahua", name: "Chihuahueno (Chihuahua)", group: "companion-toy" },
  {
    id: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    group: "companion-toy",
  },
  {
    id: "king-charles-spaniel",
    name: "King Charles Spaniel",
    group: "companion-toy",
  },
  { id: "pekingese", name: "Pekingese", group: "companion-toy" },
  { id: "japanese-chin", name: "Chin (Japanese Chin)", group: "companion-toy" },
  {
    id: "continental-toy-spaniel",
    name: "Epagneul Nain Continental (Continental Toy Spaniel)",
    group: "companion-toy",
  },
  {
    id: "russian-toy",
    name: "Russkiy Toy (Russian Toy)",
    group: "companion-toy",
  },
  { id: "kromfohrlander", name: "Kromfohrlander", group: "companion-toy" },
  { id: "pug", name: "Pug", group: "companion-toy" },
  {
    id: "french-bulldog",
    name: "Bouledogue Francais (French Bulldog)",
    group: "companion-toy",
  },
  { id: "boston-terrier", name: "Boston Terrier", group: "companion-toy" },
  { id: "prague-ratter", name: "Prague Ratter", group: "companion-toy" },
  // sighthounds
  { id: "afghan-hound", name: "Afghan Hound", group: "sighthounds" },
  { id: "saluki", name: "Saluki", group: "sighthounds" },
  {
    id: "borzoi-russian-hunting-sighthound",
    name: "Russkaya Psovaya Borzaya (Borzoi - Russian Hunting Sighthound)",
    group: "sighthounds",
  },
  { id: "deerhound", name: "Deerhound", group: "sighthounds" },
  { id: "irish-wolfhound", name: "Irish Wolfhound", group: "sighthounds" },
  { id: "greyhound", name: "Greyhound", group: "sighthounds" },
  { id: "whippet", name: "Whippet", group: "sighthounds" },
  {
    id: "hungarian-greyhound",
    name: "Magyar Agar (Hungarian Greyhound)",
    group: "sighthounds",
  },
  {
    id: "italian-sighthound",
    name: "Piccolo Levriero Italiano (Italian Sighthound)",
    group: "sighthounds",
  },
  { id: "azawakh", name: "Azawakh", group: "sighthounds" },
  { id: "sloughi", name: "Sloughi", group: "sighthounds" },
  {
    id: "polish-greyhound",
    name: "Chart Polski (Polish Greyhound)",
    group: "sighthounds",
  },
  {
    id: "spanish-greyhound",
    name: "Galgo Espanol (Spanish Greyhound)",
    group: "sighthounds",
  },
  { id: "kazakh-tazy", name: "Kazakh Tazy", group: "sighthounds" },
];
